cors:
  originPatterns: http://localhost:8080,https://erudio.com.br,http://localhost:3000
security:
  jwt:
    token:
      secret-key:53cr37
      expire-length:3600000  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useTimezone=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    hibernate:
      ddl-auto: create 
    show-sql: false
springdoc:
  pathsToMatch:
  - /auth/**
  - /api/**/v1/**
  swagger-ui:
    use-root-path: true
